name: Visa Bot

on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * *'

jobs:
  run-bot:
    runs-on: ubuntu-latest

    env:
      GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY_2 }}
      BOT_TOKEN: ${{ secrets.BOT_TOKEN_2 }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - run: pip install -r requirements.txt

      - run: python bot_visa.py
